- name: Ansible loop
  hosts: k8s
  tasks:
    - name: Create multiple files using list
      ansible.builtin.command: touch /tmp/{{ item }}.txt
      changed_when: false
      with_items:
        - cat
        - dog
        - mouse

    - name: Create multiple files using sequence
      ansible.builtin.command: touch /tmp/{{ item }}.txt
      changed_when: false
      with_sequence: '4'
